<?php $helper = $this->helper('searchbycaterory'); ?>

<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <div class="box-search-select">

        	<select class="selectpicker"  id="<?php echo $helper->getCategoryParamName() ?>" name="<?php echo $helper->getCategoryParamName() ?>">
				<option value=""><?php echo $this->__('All Categories') ?></option>
				<?php foreach ($this->getSearchableCategories() as $mainCategory): ?>
					<option value="<?php echo $mainCategory->getEntityId() ?>"><?php echo $mainCategory->getName() ?></option>
					<?php if ($helper->showSubCategories()): ?>
						<?php if ($helper->getSubCategoriesLevel() >= 2): ?>
							<?php foreach ($this->getSearchableSubCategories($mainCategory) as $category) : ?>
								<option value="<?php echo $category->getEntityId() ?>"><?php echo $helper->getIndentationText() . $category->getName() ?></option>
								<?php if ($helper->getSubCategoriesLevel() >= 3): ?>
									<?php foreach ($this->getSearchableSubCategories($category) as $subcategory3) : ?>
										<option value="<?php echo $subcategory3->getEntityId() ?>"><?php echo $helper->getIndentationText() . "&nbsp;" . $helper->getIndentationText() . $subcategory3->getName() ?></option>
										<?php if ($helper->getSubCategoriesLevel() >= 4): ?>
											<?php foreach ($this->getSearchableSubCategories($subcategory3) as $subcategory4) : ?>
												<option value="<?php echo $subcategory4->getEntityId() ?>"><?php echo $helper->getIndentationText() . "&nbsp;" . $helper->getIndentationText() . "&nbsp;" . $helper->getIndentationText() . $subcategory4->getName() ?></option>
											<?php endforeach; ?>
										<?php endif ?>
									<?php endforeach; ?>
								<?php endif ?>
							<?php endforeach; ?>
						<?php endif ?>
					<?php endif ?>
				<?php endforeach; ?>
			</select>

			<input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" class="input-text" />
				<button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><i class="fa fa-search"></i></button>
			<!--<div id="search_autocomplete" class="search-autocomplete"></div>-->
			
		</div>	
    </div>
</form>