    <style>
        .timeline-Header
        {
            display:none !important;
        }
    </style>
    <h3><?php echo $this->__('Latest Tweet') ?></h3>

    <div id="twitter-feed"><a class="twitter-timeline" data-dnt="true" data-link-color="#85c94f" href="https://twitter.com/Drchemistrycom?ref_src=twsrc%5Etfw">Tweets by Drchemistrycom</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>