<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($_info = $this->getInfo()): ?>
    <?php echo $this->getMethod()->getTitle(); ?>
    <?php if ($this->getShowCustomTextInPdf() && $_customText = $this->getMethod()->getCustomText()): ?>
        <?php echo $_customText; ?>
    <?php endif; ?>
<?php endif; ?>
